apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: devops
  name: devops
spec:
  replicas: 2
  selector:
    matchLabels:
      app: devsecops
  strategy: {}
  template:
    metadata:
      labels:
        app: devops
    spec:
      containers:
      - image: replace
        name: devops-container
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: devops
  name: devops-svc
spec:
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 4499
  selector:
    app: devops
  type: NodePort
